org.gradle.jvmargs = -Xmx8192m -XX:MaxMetaspaceSize=4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel = true
org.gradle.caching = true

loom.platform = neoForge

mod_version = 1.0.0
maven_group = me.kall.skipshelves
archives_name = skipshelves

minecraft_version = 1.21.11
mixinextras_version = 0.5.3

cf_project_id=1459898